### ISSUE TITLE
مجوز استفاده از فونت روبوتو یا امثالهم در فونت غیر آزاد

### ISSUE THREAD

**Issue by rastikerdar** [IranOpenFontGroup/Discussions#11]
من یه [فونت جدید](http://rastikerdar.blog.ir/1395/03/21/%D9%81%D9%88%D9%86%D8%AA-%D8%AC%D8%AF%DB%8C%D8%AF) طراحی کرده ام که نمی دونم آیا اجازه دارم فونت آزادی مثل روبوتو رو با فونتم ترکیب کنم و کل فونت رو بفروشم یا خیر؟
چون دیدم در یکی از فونت های تجاری معروف فارسی از فونت روبوتو برای لاتینش استفاده کرده و خب روبوتو فونت خیلی خوبیه.

اگر این اجازه وجود داره آیا باید کار خاصی هم در هنگام فروش در زمینه لایسنس انجام بدم؟

**Comment by aziz** [comment]
با توجه به بند دو و چهار لایسنس آپاچی (که روبوتو از ازش استفاده می‌کنه) میتونی این کار رو بکنی. 
بند چهار یه سری شرایط داره که به راحتی می‌تونی رعایت کنی.
1. Grant of Copyright License. Subject to the terms and conditions of
   this License, each Contributor hereby grants to You a perpetual,
   worldwide, non-exclusive, no-charge, royalty-free, irrevocable
   copyright license to reproduce, prepare Derivative Works of,
   publicly display, publicly perform, sublicense, and distribute the
   Work and such Derivative Works in Source or Object form.
2. Redistribution. You may reproduce and distribute copies of the
   Work or Derivative Works thereof in any medium, with or without
   modifications, and in Source or Object form, provided that You
   meet the following conditions:
   
   (a) You must give any other recipients of the Work or
     Derivative Works a copy of this License; and
   
   (b) You must cause any modified files to carry prominent notices
     stating that You changed the files; and
   
   (c) You must retain, in the Source form of any Derivative Works
     that You distribute, all copyright, patent, trademark, and
     attribution notices from the Source form of the Work,
     excluding those notices that do not pertain to any part of
     the Derivative Works; and
   
   (d) If the Work includes a “NOTICE” text file as part of its
     distribution, then any Derivative Works that You distribute must
     include a readable copy of the attribution notices contained
     within such NOTICE file, excluding those notices that do not
     pertain to any part of the Derivative Works, in at least one
     of the following places: within a NOTICE text file distributed
     as part of the Derivative Works; within the Source form or
     documentation, if provided along with the Derivative Works; or,
     within a display generated by the Derivative Works, if and
     wherever such third-party notices normally appear. The contents
     of the NOTICE file are for informational purposes only and
     do not modify the License. You may add Your own attribution
     notices within Derivative Works that You distribute, alongside
     or as an addendum to the NOTICE text from the Work, provided
     that such additional attribution notices cannot be construed
     as modifying the License.
   
   You may add Your own copyright statement to Your modifications and
   may provide additional or different license terms and conditions
   for use, reproduction, or distribution of Your modifications, or
   for any such Derivative Works as a whole, provided Your use,
   reproduction, and distribution of the Work otherwise complies with
   the conditions stated in this License.

**Comment by rastikerdar** [comment]
بنابراین به راحتی می تونم ترکیب و توی فایل اشاره کنم که گلیف های لاتین به همراه داده هایشان تحت کپی رایت فلان شرکت و همچنین مجوز مثلا آپاچی ۲ با این فونت ترکیب شده اند.

**Comment by artlesshand** [comment]
سلام خدمت دوستان عزیز!
واقعا خسته نباشید، من خیلی ناراحتم که فرصت نکردم مشارکت کنم...

صابر جان به نظرم یک نگاهی هم به اُپن‌سنس بنداز، من فکر میکنم همنشینی بهتری با تایپ‌فیس‌هایی که تولید می‌کنی داشته باشه

**Comment by rastikerdar** [comment]
متشکرم آقا فرزان.
آره و خوبیش اینه که لایسنسش هم مثل روبوتو هست و برای ترکیب مشکلی نداره.

از پاسختون ممنونم
